-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 10:03:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mibaseinforma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mibaseinforma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mibaseinforma` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mibaseinforma` ;

-- -----------------------------------------------------
-- Table `mibaseinforma`.`rolcontacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`rolcontacto` (
  `Idrolcontacto` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Este sera el valor id para identificar el rol de un contacto',
  `Nomrol` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo guardara los nombres de los roles que puede tener una colaborador: ejemplo vigilante',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`Idrolcontacto`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`contactos` (
  `IdContacto` INT(12) NOT NULL COMMENT 'Este campo es para guardar el numero de documento del contacto ',
  `ConNombres` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar los nombres del contacto ',
  `ConApellidos` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar los apellidos del contacto \\n',
  `ConCorreo` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar el correo del contacto ',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `rolcontacto_Idrolcontacto` INT(5) NOT NULL,
  PRIMARY KEY (`IdContacto`, `rolcontacto_Idrolcontacto`),
  INDEX `fk_contacto_rolcontacto1_idx` (`rolcontacto_Idrolcontacto` ASC),
  CONSTRAINT `fk_contacto_rolcontacto1`
    FOREIGN KEY (`rolcontacto_Idrolcontacto`)
    REFERENCES `mibaseinforma`.`rolcontacto` (`Idrolcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`curso` (
  `IdCurso` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Este sera el valor id para identificar el curso de un vocero',
  `CurNum` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Este campo guardara los cursos que puede tener un vocero ejemplo: 801',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`IdCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`materias` (
  `IdMateria` INT(5) NOT NULL COMMENT 'Este sera el valor id para identificar la materia que dicta un profesor',
  `NomMat` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo guardara las materias que esta dictando  un profesor ejemplo: SOCIALES',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`IdMateria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`usuario_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`usuario_s` (
  `usuId` INT(11) NOT NULL AUTO_INCREMENT,
  `usuLogin` VARCHAR(50) NOT NULL,
  `usuPassword` VARCHAR(100) NOT NULL,
  `usuUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `usuEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `usuRemember_token` VARCHAR(100) NOT NULL,
  `usu_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `usu_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`usuId`),
  UNIQUE INDEX `uniq_login` (`usuLogin` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`persona` (
  `perId` INT(11) NOT NULL COMMENT 'Nos muetsra el Id de la tabla persona',
  `perDocumento` VARCHAR(20) NOT NULL COMMENT 'Nos muestra el documento de la persona',
  `perNombre` VARCHAR(100) NOT NULL COMMENT 'Nos muestra el nombre de la persona',
  `perApellido` VARCHAR(255) NOT NULL COMMENT 'Nos muestra el apellido de la persona',
  `perEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `perUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `per_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `per_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_s_usuId` INT(11) NOT NULL,
  PRIMARY KEY (`perId`, `usuario_s_usuId`),
  UNIQUE INDEX `uniq_documento` (`perDocumento` ASC),
  INDEX `fk_persona_usuario_s1_idx` (`usuario_s_usuId` ASC),
  CONSTRAINT `fk_persona_usuario_s1`
    FOREIGN KEY (`usuario_s_usuId`)
    REFERENCES `mibaseinforma`.`usuario_s` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Esta tabla nos muestra los datos de la persona ';


-- -----------------------------------------------------
-- Table `mibaseinforma`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`profesores` (
  `IdProfesor` INT(12) NOT NULL COMMENT 'Este campo es para guardar el numero de documento del profesor',
  `ProNombres` VARCHAR(40) NOT NULL COMMENT 'Este campo es para guardar los nombres del vocero',
  `ProApellidos` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar los apellidos del profesor',
  `ProCorreo` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar el correo del profesor',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `materias_IdMateria` INT(5) NOT NULL,
  PRIMARY KEY (`IdProfesor`, `materias_IdMateria`),
  INDEX `fk_profesor_materias1_idx` (`materias_IdMateria` ASC),
  CONSTRAINT `fk_profesor_materias1`
    FOREIGN KEY (`materias_IdMateria`)
    REFERENCES `mibaseinforma`.`materias` (`IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`rol` (
  `rolId` INT(11) NOT NULL AUTO_INCREMENT,
  `rolNombre` VARCHAR(32) NOT NULL,
  `rolDescripcion` VARCHAR(255) NOT NULL,
  `rolEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `rolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `rol_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `rol_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`rolId`),
  UNIQUE INDEX `uniq_nombrerol` (`rolNombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`usuario_s_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`usuario_s_roles` (
  `id_usuario_s` INT(11) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `fechaUserRol` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `obsFechaUserRol` TEXT NULL DEFAULT NULL,
  `usuRolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario_s`, `id_rol`),
  INDEX `usuario_s_roles_fk_rolidrol` (`id_rol` ASC),
  CONSTRAINT `usuario_s_roles_fk_rolidrol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mibaseinforma`.`rol` (`rolId`),
  CONSTRAINT `usuario_s_roles_fk_usuario_sid`
    FOREIGN KEY (`id_usuario_s`)
    REFERENCES `mibaseinforma`.`usuario_s` (`usuId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`voceros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`voceros` (
  `IdVoceros` INT(12) NOT NULL COMMENT 'Este campo es para guardar el numero de documento del vocero',
  `VocNombres` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar los nombres del vocero',
  `VocApellidos` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar los apellidos del vocero',
  `VocCorreo` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Este campo es para guardar el correo del vocero',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `curso_IdCurso` INT(5) NOT NULL,
  PRIMARY KEY (`IdVoceros`, `curso_IdCurso`),
  INDEX `fk_voceros_curso1_idx` (`curso_IdCurso` ASC),
  CONSTRAINT `fk_voceros_curso1`
    FOREIGN KEY (`curso_IdCurso`)
    REFERENCES `mibaseinforma`.`curso` (`IdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mibaseinforma`.`Jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibaseinforma`.`Jornada` (
  `IdJornada` INT NOT NULL AUTO_INCREMENT,
  `JorNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdJornada`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
